# Tabletop Inquiry 

*On the relevance of tabletop prototyping to humanities research* | English 508 at UVic | Jentery Sayers 

This is a reflection on ["Paper Computers,"](https://jentery.github.io/508v4/) a UVic seminar on prototyping tabletop games informed by literary and media history. The term "paper computer" was coined by [Matthew Kirschenbaum](http://jenteryteaches.com/noneshall/508/kirschenbaumWar.pdf) as a way to describe tabletop games (wargames, in particular). We used it [this semester](https://jentery.github.io/508v4/keywords.html#paper-computing) to also describe paper as a medium for storage, processing, and experimentation, including experiments with play and procedural thinking. 

This document consists of three point-form lists. The first is a series of observations made while studying and prototyping paper computers this semester; it is intended to distill and document some of our conversations. The second list outlines some questions prompted by tabletop prototyping for project design in the humanities; it is intended to highlight how tabletop prototyping may apply to a broader set of research practices. The third list itemizes types of prototypes for engaging history; it is intended as a working vocabulary for prototyping as a form of criticism. Please note that this reflection is not intended to cohere. Pardon the contradictions and any typos, and thank you for your time. 

* [Observations](#observations)
* [Prompts for Project Design](#prompts-for-project-design)
* [Types of Prototypes](#types-of-prototypes)

## Observations

* Terms such as "interactive media" are common in media studies, where "interactive" may imply responding to people's decisions with automatically generated output. But "automated" and "responsive" are not synonymous with "interactive," and *interaction is not baked into media*. It is a relation, not some quality of an object. Tables or paper may afford as much interaction as screens or software. The aims and conditions of interaction, including who and what are interacting, shape its definition. (See [Gitelman](http://jenteryteaches.com/noneshall/508/gitelmanShortHistory.pdf); [Drucker](http://jenteryteaches.com/noneshall/508/druckerAB.pdf).) 
* Immersion is not baked into media, either. *Repetition, flow, and engagement depend on context and interest.* While some people may be immersed in rulebooks, others may be immersed in oral stories. Even if media envelop us (e.g., virtual reality and theatre), experiences of them may be alienating, distracting, or uncomfortable. Of course, immersion is also a strategy for producing dedicated consumer bases, who binge and buy expansions. (See [Kirschenbaum](http://jenteryteaches.com/noneshall/508/kirschenbaumWar.pdf).) 
* Tabletop handbooks and game manuals are entry points into the opaque worlds of algorithms (i.e., procedures or formulas for conducting specific actions), and thus prototyping game rules may foster procedural literacy without requiring computer programming. *Paper games are low-tech computers, where people not only convert input into output but also translate game states into game views*. While algorithms may shape and even determine decision-making, they are also used for craft, play, and storytelling. (See [Alder](https://buriedwithoutceremony.com/); [Childres](http://www.cephalofair.com/gloomhaven); [Galloway](http://cultureandcommunication.org/galloway/debord-ai); [Kirschenbaum](http://jenteryteaches.com/noneshall/508/kirschenbaumWar.pdf); [Nowviskie](https://quod.lib.umich.edu/d/dh/12544152.0001.001/--pastplay-teaching-and-learning-history-with-technology?g=dculture;trgt=div2_ch7;view=fulltext;xc=1).)
* The word "digital" may be misleading or reductive. Not all electronic computing is digital, and not all paper computing is analogue. More important, paper computing shows how *most novelty associated with digital media and culture predates personal computing and the internet*. We might therefore ask how today's use of "digital" is value-laden: less about material or historical particulars and more about buzz and markets. (See [Chun](http://jenteryteaches.com/noneshall/508/chunNewMedia.pdf); [Flanagan](http://jenteryteaches.com/noneshall/508/flanaganBoardGames.pdf).)
* *Paper computing asserts the centrality of embodied labour* to histories of science and technology. The work of paper processing and maintenance often goes unattributed and is routinely gendered and racialized in the name of lone male invention. Roberto Busa, for instance, did not credit the female punch-card operators who were his associates, while Josephine Miles did credit her collaborators. (See [Terras](http://melissaterras.blogspot.com/2013/10/for-ada-lovelace-day-father-busas.html); [Buurma and Heffernan](https://modernismmodernity.org/forums/posts/search-and-replace).) 
* Designers do not argue for an actual boundary between games and the outside world. *The "magic circle" does not exist in any scientific or empirical sense* (hence the word, "magic"); however, it is a common device for believability and trust. It is also used to test and sell games, and to produce meaning through play. (See [Zimmerman](https://www.gamasutra.com/view/feature/135063/jerked_around_by_the_magic_circle_.php); [Hammer and Baker](http://theenemyreader.org/wp-content/uploads/2014/02/Hammer_Baker_The_Enemy.pdf).) 
* Tabletop games manipulate space and time. Most obviously, they cast progress through tracks and counters, and they sculpt space through boards and miniatures. Yet *tabletop games also shape how time and space are perceived and experienced.* Stewart: "30 minutes would be experienced in 5 minutes at 1/12 scale and in 2.5 minutes at 1/24 scale" (66). (See [Stewart](http://jenteryteaches.com/noneshall/508/stewartOnLonging.pdf); [Krasniewicz](https://thewonderofminiatures.com/2015/05/20/miniature-manifesto-part-1-call-us-makers/).)
* *Histories of tabletop games correspond with histories of manifestos, artists' books, and zines*, especially since the 1850s. Each involves experiments with paper and, more generally, mediation, even though their audiences and cultures differ. Each is also a medium for "action writing," which either prompts actions or contains charged design elements. But, with the exception of Surrealism and Situationism, tabletop games are usually ignored in histories of the "avant-garde." (See [Caws](http://jenteryteaches.com/noneshall/508/cawsManifesto.pdf); [Drucker](http://jenteryteaches.com/noneshall/508/druckerAB.pdf); [Radway](http://jenteryteaches.com/noneshall/508/radwayZines.pdf); [Marcus](https://archive.nytimes.com/www.nytimes.com/books/98/04/26/bookend/bookend.html).)
* Perhaps ironically, *both critical play and magic circles may resist cultures of 24/7 work, productivity, and attention economics*. For many people, play is essential to self-care and community; for others, it is a form of subversion (e.g., against gamification); it is also a way to escape into intense focus and dedication (e.g., campaigns). Dismissing it outright as "uncritical" or "complicit" bypasses its nuance, or at least people's needs and desires for leisure and social activity. (See [Flanagan](http://jenteryteaches.com/noneshall/508/flanaganIntroCP.pdf); [Scholz](https://www.routledge.com/Digital-Labor-The-Internet-as-Playground-and-Factory/Scholz/p/book/9780415896955); [Beller](https://www.upne.com/1584655828.html); Hammer and Baker](http://theenemyreader.org/wp-content/uploads/2014/02/Hammer_Baker_The_Enemy.pdf).)
* The themes and mechanics of tabletop games frequently resemble the aesthetics and techniques of science fiction and fantasy. Here, *speculation should not be relegated to whimsy.* Delany: "one cannot revise an image until one has an image to revise. . . . If you don't see it, you can't work for it" (31). (See [Delany](http://jenteryteaches.com/noneshall/508/delanyTomorrows.pdf); [Hammer and Baker](http://theenemyreader.org/wp-content/uploads/2014/02/Hammer_Baker_The_Enemy.pdf).) 
* The practices of writing, storytelling, and design address someone; however, *the notion of "users" is extremely limited.* It tends to flatten subjectivity and be market-driven. It may also ignore strategies of mis- or non-use. And yet alternative terms, such as "audiences," "consumers," and "players," may be no better. Ditto with the term, "gamers," which can be both homogenizing and exclusionary. People may be interested in games without identifying as gamers, or they may be curious about games but skeptical of gaming cultures. (See [Burdick](http://jenteryteaches.com/noneshall/508/burdickMeta.pdf); [Beltrán](https://www.tor.com/2015/04/27/why-minority-settings-in-rpgs-matter/%22).)
* Tabletop cultures, design studies, and critical theory are all discourse communities with their own lexicons and rules, which people use to belong *and* to police. Even though media are irreducible to language (e.g., they are more than what people say about them), the creation and persistence of discourse communities matter for media practice and culture. *Alternative approaches to games, design, and theory often require new discourse communities.* Language is a type of action. (See [Game Speak](https://jentery.github.io/508v4/keywords.html#game-speak); [Design Speak](https://jentery.github.io/508v4/keywords.html#design-speak); [Theory Speak](https://jentery.github.io/508v4/keywords.html#theory-speak).)  
* The politics of tabletop games emerge through both mechanics and themes. Consider the colonialism of settler themes and area control mechanics, the cisheteronormativity of many romance themes, the default whiteness of most character art and settings, the ableism of movement programming, the capitalism of auction and accumulation mechanics, the proliferation of predominantly white male conventions and gaming groups . . . Players not only read game rules and learn themes but also perform and inhabit their dynamics, and most games do not assume critical positions on history or power. Yet many designers, including indie designers, are working to change games from the inside, and the arts and humanities have much to contribute to this process. Change happens through themes, mechanics, and representation as well as culture, habits, and markets. (See [LaPensée](http://analoggamestudies.org/2016/03/indigenous-board-game-design-in-the-gift-of-food/); [Nahanee](https://decolonizingpractices.org/); [Beltrán](https://www.tor.com/2015/04/27/why-minority-settings-in-rpgs-matter/%22); [Rael](https://www.aaihs.org/seriously-boardgames-yes-seriously/); [Shelby](http://pwp.gatech.edu/suffragetto/); [Valens](https://twitter.com/valens116); [Boss](http://www.blackgreengames.com/about/); [Hammer and Baker](http://theenemyreader.org/wp-content/uploads/2014/02/Hammer_Baker_The_Enemy.pdf).)

## Prompts for Project Design

* *When might low-tech or lo-fi approaches be useful?* Design often starts with software or programming, which may involve steep learning curves. Low-tech approaches, such as wireframing or paper prototyping, not to mention text editors and mobile phones, may help people to focus more on core concepts and experiences. They may also help people to reduce the scope and feature creep common to many tools and platforms. (See [Burdick](http://jenteryteaches.com/noneshall/508/burdickMeta.pdf); [Kraus](http://jenteryteaches.com/noneshall/508/krausFaultlines.pdf).)  
* *How is project design also inquiry?* Rather than treating the design process as a trivial or routinized means to an end (namely, the creation of product), iteration may think through (or with, or against) techniques and materials. After all, design happens *in medias res*. It can also function as ontological theatre: the use of scenarios, media, or performance to stage engagement and experimentation instead of re-presentation. (See [Rosner](http://jenteryteaches.com/noneshall/508/rosnerDesign.pdf); [Kraus](http://jenteryteaches.com/noneshall/508/krausFaultlines.pdf); [Pickering](https://www.press.uchicago.edu/ucp/books/book/chicago/C/bo8169881.html).)
* *How do projects prompt speculations about the past?* Speculation may brush against tendencies to "discover" materials, "reveal" truths, explain away the ghosts, and make "claims" with computers. It privileges contingency of relations *and* responsibility for distinctions made, without reducing research to interpretative abandon. (See [Kraus](http://jenteryteaches.com/noneshall/508/krausFaultlines.pdf); [Dunne & Raby](https://mitpress.mit.edu/books/speculative-everything); [Lukens and DiSalvo](http://jenteryteaches.com/noneshall/508/lukensDisalvoDesign.pdf).)
* *How do projects remediate or transform historical materials, and how are they conscious of and responsible for those changes?* Remediation necessarily affects the composition and interpretation of the past, yet it also shapes people's sense of immediacy and hypermediacy. It demands attention to provenance and attribution as well. (See [Bolter and Grusin](https://mitpress.mit.edu/books/remediation); [Samuels and McGann](http://jenteryteaches.com/noneshall/508/samuelsMcGannDeformance.pdf); [Galloway](http://cultureandcommunication.org/galloway/debord-ai); [Chen](https://humangames.lab.uiowa.edu/games/mark); [Hansen and Kraus](https://docs.google.com/document/d/1SfNJ3P-07ngHakJAHNKaTCDYYSvZDBxr0i_MCctRsbs/edit); [Konkol](http://jenteryteaches.com/noneshall/508/konkolLoy.pdf); [Shelby](http://pwp.gatech.edu/suffragetto/).) 
* *How do projects engage historical materials through "design for effect" (what happened) and "design for cause" (why something happened)?* Examining both approaches acknowledges project design as a phenomenological and epistemological process. It also helps people to distinguish between simulating, reconstructing, and prototyping the past. (See [Pulsipher](https://pulsiphergames.com/Articles/DesigningforCausevsEffect.htm); [Kirschenbaum](http://jenteryteaches.com/noneshall/508/kirschenbaumWar.pdf).)
* *How do projects organize information?* Consider the five hat racks: similarity, time, location, alphabet, and continuum / magnitude. Also consider how text is a visual medium (and not just words). It is designed through layout and typography; it is arranged and used, not just seen and read. (See [Wurman](https://books.google.ca/books?id=zUhiAAAAMAAJ&q=five+hat+racks+design+principle++Wurman&dq=five+hat+racks+design+principle++Wurman&hl=en&sa=X&ved=0ahUKEwil3NWN84bfAhWDOn0KHcxMDcYQ6AEIKjAA); [Gitelman](http://jenteryteaches.com/noneshall/508/gitelmanShortHistory.pdf); [Buurma and Heffernan](https://modernismmodernity.org/forums/posts/search-and-replace).)
* *How do projects rely on alphabetic language(s), and which language(s)?* Some areas of design consider the degree to which a project works across or without alphabetic languages. For example, "language independence" relies heavily on icons to facilitate interpretation. These practices also raise questions about the dominance of English in media production.
* *How do embodied dynamics (such as play, interaction, and interpretation) entwine aesthetics with mechanics?* Engagement is not disembodied, and mechanics do not always determine use. Attention to embodied dynamics also underscores the importance of [accessibility](http://gameaccessibilityguidelines.com/) to design. (See [Hunicke, LeBlanc, and Zubek](http://jenteryteaches.com/noneshall/508/hunickeMDA.pdf).) 
* *How are projects documented, and with which futures in mind?* Design documents and repositories present a narrative about how this became that. Although they share process, they are also crafted and edited. They do not "capture" what actually happened so much as communicate a framed story of development. That story and its contents may be re-used or re-purposed by others in the future, and the needs and interests of future audiences are not easy to anticipate.
* *How do projects progressively disclose information?* Not all of the project's material can (and probably shouldn't) be presented from the start. What is disclosed, how, when, and where says a lot about a project and its approach to performance load and argumentation. Also, projects may benefit from extending tasks or events (e.g., legacy games). The Zeigarnik effect claims that interrupted or incomplete tasks are better remembered than completed tasks. (See [Lidwell, Holden, and Butler](https://link.springer.com/article/10.1007/s11423-007-9036-7).)     
* *How are projects tested?* All too often, projects are designed without situations of use in mind; they may be driven by abstract or ideal notions of their audiences and contexts. Alternatives include sharing projects before they're ready, observing (like a fly on the wall) how people interact with drafts and prototypes, and prompting people to reach specific results or conclusions. (See [Hammer et al.](http://playtestingworkshops.com/).)  
* *How do we study the expected and unexpected use patterns ("wear and tear") of projects?* Repeated use is often associated with maintenance rehearsal, whereas elaborative rehearsal may involve misuse, repurposing, modding, and "desire lines" (creative shortcuts). Designs may encourage both maintenance and elaborative rehearsal as types of use. Not all uses must be anticipated or expected, and project design can be described as facilitation (e.g., providing context) instead of control. (See [Kraus](http://jenteryteaches.com/noneshall/508/krausFaultlines.pdf); [Lidwell, Holden, and Butler](https://link.springer.com/article/10.1007/s11423-007-9036-7).)

## Types of Prototypes 

Here are some types of prototypes for engaging history. I've used the framework of "source materials," but perhaps you prefer "texts" or the like. 

* *Imitation* (labour of source material): to better understand the composition of source material by learning the techniques involved in its production
* *Forgery* (economy of source material): to better understand the public perception and/or value of source material by learning the techniques involved in its production, but with intent to either deceive or reveal deception
* *Scenario* (interaction with source material): to better understand how people may ultimately interpret source material by situating it in contexts of use and then observing those uses
* *Story* (performance of source material): to better understand how source material gains cultural traction or builds identity by treating it as a script and performing it on or off record
* *Counterfactual* (norms or conditions of source material): to better understand the biases of source material (or common interpretations of it) by constructing “what-if” alternatives to specific aspects of its history, content, or composition 
* *Model* (logic or conventions of source material): to better understand the mode, form, genre, scale, or design of source material by rendering it as an abstraction, using it to alter other source materials (or aspects of itself), and determining why the changes are interesting (if at all)
* *Wish* (ideology of source material): to better understand the worldviews, belief systems, or desires of source material by increasing/decreasing their frequency, reversing them, or otherwise manipulating them and then determining why the changes are interesting (if at all)

Prototyping may be considered a form of criticism that:

* Performs a method or physically *manifests a way of reading* through techniques such as imitation, alteration, scripting, repetition, simulation, recontextualization, modelling, counterfactuals, ruination, and trial-and-error testing, to name a few.
* Is interpreted or assessed based on its *effectiveness as an experiment*, or how persuasively it changes or isolates the systems through which materials and contexts afford meaning. Such systems may include matters of perception (e.g., how materials are seen or engaged), semantics (e.g., how signifiers relate and produce meaning), aesthetics (e.g., how materials are arranged and composed), politics (e.g., how materials enable or are embedded in ideologies), history (e.g., how materials are anchored in time and space but also move across them), matter (e.g., the stuff of which materials are made), and want or need (e.g., wishes, desires, uses, and applications).
* Expresses a form or model, which foregrounds use and *prompts specific actions*. Such actions may include writing in a margin or blank space, entering data, replying to a message, fixing a bug, following steps, signing, clicking, copying, pasting, deleting, scanning, redacting, searching, tagging, spamming, non-communication (e.g., in the case of frustration, silence, or confusion), or simply listening, watching, or reading. The consequences of these actions are not always predictable. In fact, the most persuasive prototypes foster surprise.
* Articulates language and meaning with matter. While prototypes are conceptual, they demonstrate (as opposed to re-present) how concepts *work through materials* and settings. 
* Suggests or conjectures something instead of proving it. That is, a prototype is a *situation for interpretation*, not a standalone object. Meaning is an effect of experimentation, not an ingredient of it.
* Imagines a solution or *scenario* to examine the results. Such scenarios may include improving features of source material, stewarding it into the present, remediating it, remaking it, repairing it, or (to demonstrate why it was persuasive in the first place) ruining it. Any of these practices may experiment with alternate histories, probable futures, adjacent possibilities, or absences in the archive.
* Often uses *ephemerality as a medium*. That is, it tends to be more interested in what escapes than what persists. Here, we may consider how interactions, interfaces, performances, rhythms, impressions, feelings, and affects escape the record or are difficult to “capture” with technologies. Put this way, loss is not necessarily an anxiety or emphasis. Change becomes the most interesting or suggestive element of creativity and criticism.

Prototyping also asks how source materials address us (see [Mitchell](https://mediatropes.com/index.php/Mediatropes/article/view/1771)): 

* Source materials function as public documents, intended for passersby. Here, negative space, lines, typefaces, and font sizes are especially important (e.g., graphic design). The material *wants your attention*. It is charged. It is read from a distance.
* Source materials become symbols, intended for extended observation. Here, the form or “face” across components is key (e.g., topography). The material *wants to escape reality*. It welds feeling with arrangement, against the reduction of signs to mere vehicles for meaning.
* Source materials manifest ways of reading, intended for familiarization or defamiliarization. Here, orientation, embodiment, and eye movement are most significant (e.g., interface design). The material *wants to afford certain readings*. It influences or even structures vision.
* Source materials create relations with other materials, intended for the production or analysis of patterns. Here, juxtaposition and reference are central (e.g., interaction design). The material *wants to be an index*, with readers traversing across (or toggling between) it and something else. It connects.
* Source materials are proof, intended as evidence. Here, the truth claims are emphasized (e.g., forensics). The material *wants to be a record*. It is like a photograph or signature. It points or demonstrates.
* Source materials are objects or commodities, intended for collection and exhibition. Here, the value, availability, and economy of materials are privileged (e.g., book arts). The material *wants to be displayed*. People travel to witness the original. Something about it cannot be copied.
* Source materials are scans, intended primarily for access on screen. Here, recognition, formats, and relations between witnesses, editions, originals, and copies are the focus (e.g., versioning). The material *wants to be found or archived*. It is its legibility.
* Source materials are edges, intended to produce boundaries. Here, page size, margins, paper, screens, and canvases matter (e.g., layout design). The material *wants to frame language and reading*. It demarcates.
* Source materials are windows or portals, intended for transparency. Here, clarity is everything (e.g., instrumental design). The material *gives people want they want or expect*. It is a vehicle for exchange.
* Source materials are mirrors, intended for reflection or re-presentation. Here, a lack of ornament, a use of familiar features, and an insistence on accuracy of perspective are significant (e.g., isomorphic design). The material *wants to express the world precisely and/or prompt awareness* (or social- or self-awareness). It hails.
* Source materials are tactile, intended for handling and touching. Here, texture is paramount (e.g., materials design). The material *wants to be tangible*, or it does not want to be behind glass or screen. It exposes the limits of vision and ocularcentrism.
* Source materials are processes, intended to resist alienation or abstraction. Here, composition, traces of interaction, gradual change, and the time spent making, reproducing, preserving, and disposing are most important (e.g., labour studies). The material *wants to be a verb*. It is mutable. It decays, rots, morphs, grows. It is also linked to various “invisible” contributors and acts of production.
* Source materials are dogma, intended for followers. Here, lists, point form, and order are foregrounded (e.g., litany). The material *wants to be copied*, distributed, consulted, and observed. It directs or guides.
* Source materials are policy or law, intended for nations, citizens, or employees. Here, an absence of aesthetics, a lack of variation, or an assertion of consistency is crucial (e.g., protocol). The material does not want to be an image. It *wants to be code or procedure*, with a standard. It is executable.
